MyFirstASPWebApp/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPWebApp.Models
{
    public class CalculatorModel
    {
        [Required]
        [Range(0, 100)]
        public float assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public float groupprojects { get; set; }
        [Required]
        [Range(0, 100)]
        public float quizzes { get; set; }
        [Required]
        [Range(0, 100)]
        public float exams { get; set; }
        [Required]
        [Range(0, 100)]
        public float intex { get; set; }

    }
}

MyFirstASPWebApp/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstASPWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPWebApp.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculator(CalculatorModel model)
        {
            return View();
        }
    }
}

MyFirstASPWebApp/Views/Blah/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Calculator";
}

@model CalculatorModel

<h2>Grade Calculator:</h2>
<form method="post">
    <label>Assignments (55%):</label>
    <input type="number" id="assignments" asp-for="assignments"/><br />
    <label>Group Projects (5%):</label>
    <input type="number" id="groupprojects" asp-for="groupprojects"/><br />
    <label>Quizzes (10%):</label>
    <input type="number" id="quizzes" asp-for="quizzes"/><br />
    <label>Exams (20%):</label>
    <input type="number" id="exams" asp-for="exams"/><br />
    <label>INTEX (10%):</label>
    <input type="number" id="intex" asp-for="intex"/><br />
    <input type="submit" value="Submit Grades" id="submit" />

    <div asp-validation-summary="All"></div>
</form>
<br />

<script src="~/js/calculator.js"></script>

MyFirstASPWebApp/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Homepage";
}


<header>David Jensen</header>

<img src="img/dave.jpg" />

<p>
    I am looking forward to IS413 in the winter 2022 semester.
    I really hope to learn valueable and applicable skills that i can use int the real world.
    I am also looking forward to the react unit as that is what i will be working in with my internship this summer.
    I also hope to learn how to learn a little better so i will be more teachable in the future.
</p>

<p>
    Top #3 jobs I am most interested in pursuing when I graduate:
</p>

<ul>
    <li>Product Management</li>
    <li>Business Intelligence</li>
    <li>F1 Driver</li>
</ul>

MyFirstASPWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/Styles.css" rel="stylesheet" />
    <link href="/img/3240662.ico" rel="icon" type="image/x-icon" />
</head>
<body>

    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="Calculator">Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>